name: Fetch latest data

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '25 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -vv --time-cond data_latest.json -o data_latest.json https://c19downloads.azureedge.net/downloads/data/data_latest.json
        jq . data_latest.json
        curl -vv --compressed --time-cond utlas.geojson -o utlas.geojson https://c19pub.azureedge.net/utlas.geojson
        jq . utlas.geojson
        curl -vv --compressed --time-cond countries.geojson -o countries.geojson https://c19pub.azureedge.net/countries.geojson
        jq . countries.geojson
        curl -vv --compressed --time-cond regions.geojson -o regions.geojson https://c19pub.azureedge.net/regions.geojson
        jq . regions.geojson
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
